services:
  - type: web
    name: sampling-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
